package net.beans.www;

import enumerations.Contact_Method;
import org.aspectj.lang.annotation.Aspect;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;

/**
 * <h5>public class ContactFormBean</h5>
 * <P>This source-code file simulates a bean with generated fields from an HTML contact form.</P>
 * <p>This class is designed to allow extension to ContactFormBean subclasses such as a form for an employer to fill out adding organization, pay rate, wage types, salary range ect..</p>
 * <p>The oritected access modifier will allow subclass to view and manipulate it's fields directly without the need for calling set* or get*</p>
 */
@Component
public class ContactFormBean {

    protected String firstName;
    protected String lastName;
    protected String telephone;
    protected String eMail;
    protected Contact_Method method;
    protected String message;
    protected static final Logger logger = LoggerFactory.getLogger(ContactFormBean.class);
    /**
     * <p>This field is auto-generated by MySQL AUTO_INCREMENT INT</p>
     */
    protected int id;

    public ContactFormBean(String firstName, String lastName, String telephone, String eMail, Contact_Method method, String message) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.telephone = telephone;
        this.eMail = eMail;
        this.method = method;
        this.message = message;

    }

    public ContactFormBean()
    {

    }

    protected void log(String str)
    {
        logger.atInfo();
        logger.info(str);
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String geteMail() {
        return eMail;
    }

    public void seteMail(String eMail) {
        this.eMail = eMail;
    }

    public Contact_Method getMethod() {
        return method;
    }

    public void setMethod(Contact_Method method) {
        this.method = method;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }


    public int getId(){return this.id;}
    public void id( int id)
    {
        this.id=id;
    }



    @Override
    public String toString() {
        return "ContactFormBean{" +
                "firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", telephone='" + telephone + '\'' +
                ", eMail='" + eMail + '\'' +
                ", method=" + method +
                ", message='" + message + '\'' +
                '}';
    }


}
